services:
  db:
    image: postgres:15
    env_file: .env
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 5s
      retries: 20
  backend:
    build: { context: ., dockerfile: Dockerfile.dev }
    env_file: .env
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports: ["3001:3000"]
    depends_on:
      db: { condition: service_healthy }
    restart: unless-stopped
volumes:
  db_data:
  bundle_data:
